### ISSUE TITLE
Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by ramsestom** [tsjing/socket.io-client#2]
when trying to use it with react-native 0.30 here is the error I get at runtime as soon as I have the line `import io from 'react-native-socket.io-client/socket.io.js';`  in my code:

```
Cannot read property 'match' of undefined
Module AppRegistry is not a registered callable module.
```

**Comment by hilkeheremans** [comment]
We will be updating as we will soon move to RN 0.30 ourselves. Feel free to track down what's wrong and submit a PR!

**Comment by ramsestom** [comment]
Fixed it replacing

`var isAndroid = navigator.userAgent.match(/Android/i);`

by

`var isAndroid = typeof navigator !== 'undefined' && /Android/i.test(navigator.userAgent);`

in socket.io.js (line 2985)

(I tried defining the "navigator.userAgent" property in my react-native code with 

```
if (window.navigator && Object.keys(window.navigator).length == 0) {
  window = Object.assign(window, {navigator: {userAgent: 'react-native'}}); 
}
```

before calling the io import but it did not work (probably because all imports of a class are performed before the rest of the code...))

**Comment by hilkeheremans** [comment]
Well, the reason we're not experiencing this in our apps is probably because we patch `global.navigator.userAgent = 'ReactNative'`. We do this in order to use a specific id generation library called `cuid`. For reasons varied, in practice, this would work as follows (close to the app entry point):

```
// workaround for React Native bug with cuid
if (global.navigator && global.navigator.product === 'ReactNative') {
    global.navigator.mimeTypes = '';
    try {
        global.navigator.userAgent = 'ReactNative';
    }
    catch (e) {
        console.log('Tried to fake useragent, but failed. This is normal on some devices, you may ignore this error: ' + e.message);
    }
}
```

This may also form a (more robust, app-wide) workaround for you, as well as for #1, but I have not tested our apps on RN 0.30 yet so cannot confirm.

**Comment by ramsestom** [comment]
your solution is working in RN 0.30 too. Thanks
